# name: Deploy to DO

# on:
#   push:
#     branches: [ main ]
#   # Allows to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   deploy:

#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout the thing
#         uses: actions/checkout@v2
#       # Push changes to the DO server
#       - name: Push the thing
#         run: |
#           git remote add live ${{ secrets.DO_REMOTE }}
#           git push live main
#       # Logs into the DO server and restarts (what I do manually now)
#       - name: Try to restart the server
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           key: ${{ secrets.KEY }}
#           username: ${{ secrets.USERNAME }}
#           script: ""
